apiVersion: v1
kind: Pod
metadata:
  name: tracker-docker
  labels:
    app: tracker-docker
spec:
  hostname: mysql
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: trainer
    - name: MYSQL_USER
      value: trainer_user
    - name: MYSQL_PASSWORD
      value: trainer_pass
    ports:
    - containerPort: 3306
  - name: tracker-docker
    image: dockerdabz/trainer-tracker
    ports:
    - containerPort: 8080
---
        
apiVersion: v1
kind: Service
metadata:
  name: tracker-docker
  labels:
    run: tracker-docker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: tracker-docker
---